# Generated by Django 3.2.5 on 2021-07-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uan', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('uan', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('uan', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
