# Generated by Django 3.2.5 on 2021-11-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20210924_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-id']},
        ),
    ]
