# Generated by Django 3.2.5 on 2021-07-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20210717_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='usd',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='usd',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='usd',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
