# Generated by Django 3.2.5 on 2021-07-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20210717_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='usd',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='usd',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='usd',
        ),
    ]
