# Generated by Django 3.2.5 on 2021-07-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20210717_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
