# Generated by Django 3.2.5 on 2021-07-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_auto_20210717_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
