# Generated by Django 3.2.5 on 2021-07-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_delete_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
